/*
 * PopUpFrame.java
 *
 * Created on May 22, 2001, 6:56 PM
 */

package gui;

/**
 *
 * @author  isc
 * @version 
 */
public class PopUpFrame extends javax.swing.JFrame {

    private String msg, title;
    
    /** Creates new form PopUpFrame */
    public PopUpFrame(String text) {
        msg = text;
        title = "Alert";
        initComponents ();
        pack ();
    }

    public PopUpFrame(String text, String name) {
        msg = text;
        title = name;
        initComponents ();
        pack ();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));
        setTitle(title);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        jLabel1.setText(msg);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        getContentPane().add(jLabel1);
        
        
        OKButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OKButton.setName("okButton");
        OKButton.setText("OK");
        OKButton.setDefaultCapable(false);
        OKButton.setMargin(new java.awt.Insets(2, 7, 2, 7));
        OKButton.setContentAreaFilled(false);
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        }
        );
        
        getContentPane().add(OKButton);
        
    }//GEN-END:initComponents

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Add your handling code here:
      dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
/*    public static void main (String args[]) {
        new PopUpFrame ("this is bollocks!").show ();
    }
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton OKButton;
    // End of variables declaration//GEN-END:variables

}
