/*
 * PopUpFrame.java
 *
 * Created on May 22, 2001, 6:56 PM
 */

package gui;

import java.awt.*;
/**
 *
 * @author  isc
 * @version 
 */
public class PopUpFrame extends javax.swing.JFrame {

    private String msg, title;
    private Frame[] OpenedFrames;
    
    /** Creates new form PopUpFrame */
    public PopUpFrame(String text) {
        msg = text;
        title = "Alert";
        initComponents ();
        OpenedFrames = getFrames();
        for (int i=0; i<(OpenedFrames.length-1); i++){
            OpenedFrames[i].disable();
            System.out.print(i+"\n");
        }
        pack ();
        setLocation((500-this.getWidth())/2,(500-this.getHeight())/2);
    }

    public PopUpFrame(String text, String name) {
        msg = text;
        title = name;
        initComponents ();
      pack ();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        PopUpPanel = new java.awt.Panel();
        TextMsg = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));
        setName("popUpFrame");
        setTitle(title);
        setForeground(java.awt.Color.lightGray);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTyped(evt);
            }
        }
        );
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        PopUpPanel.setLayout(new java.awt.GridLayout(2, 1));
        PopUpPanel.setFont(new java.awt.Font ("Dialog", 0, 11));
        PopUpPanel.setName("popUpPanel");
        PopUpPanel.setBackground(new java.awt.Color (204, 204, 204));
        PopUpPanel.setForeground(java.awt.Color.black);
        
        TextMsg.setPreferredSize(new java.awt.Dimension(250, 30));
          TextMsg.setName("textMsg");
          TextMsg.setMinimumSize(new java.awt.Dimension(100, 16));
          TextMsg.setText(msg);
          TextMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          TextMsg.setMaximumSize(new java.awt.Dimension(2000, 30));
          PopUpPanel.add(TextMsg);
          
          
        OKButton.setPreferredSize(new java.awt.Dimension(90, 30));
          OKButton.setMaximumSize(new java.awt.Dimension(180, 30));
          OKButton.setFocusPainted(false);
          OKButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          OKButton.setName("okButton");
          OKButton.setText("OK");
          OKButton.setDefaultCapable(false);
          OKButton.setContentAreaFilled(false);
          OKButton.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  OKButtonActionPerformed(evt);
              }
          }
          );
          PopUpPanel.add(OKButton);
          
          
        getContentPane().add(PopUpPanel);
        
    }//GEN-END:initComponents

  private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
    for (int i=0; i<(OpenedFrames.length-1); i++){
        OpenedFrames[i].enable();
    }
    dispose();
  }//GEN-LAST:event_OKButtonActionPerformed

  private void keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyTyped
    // this routine should filter "Return" and "Space" keyevents only!!!!
    for (int i=0; i<(OpenedFrames.length-1); i++){
        OpenedFrames[i].enable();
    }
    dispose();
  }//GEN-LAST:event_keyTyped

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Add your handling code here:
//  this button does not exist!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
//    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        for (int i=0; i<(OpenedFrames.length-1); i++){
            OpenedFrames[i].enable();
        }
        dispose();
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
/*    public static void main (String args[]) {
        new PopUpFrame ("this is bollocks!").show ();
    }
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel PopUpPanel;
    private javax.swing.JLabel TextMsg;
    private javax.swing.JButton OKButton;
    // End of variables declaration//GEN-END:variables

}
