###################################################################
## $Id: Makefile,v 1.5 2001-07-19 17:57:58 swprakt Exp $
###################################################################


all:
	java io.Main "sfc1.tsfc"


sfc2:
	java io.Main "sfc2.tsfc"

mutex2:
	java io.Main "mutex2.tsfc"
