# $Id: Makefile,v 1.1 2001-04-20 17:28:11 swprakt Exp $
###############################################
LOCALDOCDIR=Doc

################################################



clean:
	\rm -f *.html *.css  *~ package-list
	\rm -f ./absynt/*.html
	rmdir ./absynt

