#----------------------------------------------------------------------
# local makefile
# $Id: Makefile,v 1.1 2001-04-20 17:37:42 swprakt Exp $
#----------------------------------------------------------------------


PACKAGEDIRS = absynt  utils editor gui checks1 parser\
	      modcheck simulator position1 position2

################################################

clean: ;
	rm -rf $(PACKAGEDIRS)
	rm -f *.html *.css package-list
	rm -f specification.txt





