########################################################
## $Id: Makefile,v 1.1 2001-04-20 17:32:24 swprakt Exp $
########################################################


WWWDIR      = /home/info/www/inf/deRoever/SS00/Java/Mist

www:
	cp *.html  $(WWWDIR)
